Gest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    path('militares/', include('militares.urls', namespace='militares')),
    path('contatos/', include('contatos.urls', namespace='contatos')),
    path('documentos/', include('documentos.urls', namespace='documentos')),
    path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

militares/urls.py
from django.urls import path
from .views import Fatosobservados, Pesquisafatosobs, Fatosobservadospessoa, \
    Criarmilitar, Criarobservacao, Perfilmilitar, \
    Updateobservacao, Criardestino, Verdestino, Updatedestino, \
    Fatd, Fdi, Mapaforca

app_name = 'militares'

urlpatterns = [
    path('fatosobservados/novo', Criarobservacao.as_view(), name='criarobservacao'),
    path('fatosobservados', Fatosobservados.as_view(), name='fatosobservados'),
    path('fatosobservados/pesquisa', Pesquisafatosobs.as_view(), name='pesquisafatosobs'),
    path('fatosobservados/<int:pk>', Fatosobservadospessoa.as_view(), name='fatosobservadospessoa'),
    path('fatosobservados/update/<int:pk>', Updateobservacao.as_view(), name='updateobservacao'),
    path('cadastro/', Criarmilitar.as_view(), name='criarmilitar'),
    path('perfil/<int:pk>', Perfilmilitar.as_view(), name='perfilmilitar'),
    path('fatosobservados/fatd/<int:pk>', Fatd.as_view(), name='fatd'),
    path('fatosobservados/fdi/<int:pk>', Fdi.as_view(), name='fdi'),
    path('destino', Verdestino.as_view(), name='destino'),
    path('destino/update/<int:pk>', Updatedestino.as_view(), name='updatedestino'),
    path('destino/novo', Criardestino.as_view(), name='criardestino'),
    path('destino/mapa_forca', Mapaforca.as_view(), name='mapa_forca'),
]

pessoas/urls.py
from django.urls import path
from .views import Cadastro, \
    Cadastropessoa, \
    Criarpessoa, \
    Delete, \
    Perfilpessoa, \
    ListConscrito, \
    ReadConscrito, \
    Formulario, \
    Pesquisacadastro

app_name = 'pessoas'

urlpatterns = [
    path('cadastro', Cadastro.as_view(), name='cadastro'),
    path('cadastro/pesquisa', Pesquisacadastro.as_view(), name='pesquisacadastro'),
    path('cadastro/<int:pk>', Cadastropessoa.as_view(), name='cadastropessoa'),
    path('cadastro/novo', Criarpessoa.as_view(), name='criarpessoa'),
    path('cadastro/delete/<int:pk>', Delete.as_view(), name='delete'),
    path('perfil/<int:pk>', Perfilpessoa.as_view(), name='perfilpessoa'),
    path('cadastro/listconscrito', ListConscrito.as_view(), name='listconscrito'),
    path('cadastro/readconscrito/<int:pk>', ReadConscrito.as_view(), name='readconscrito'),
    path('cadastro/formulario/<int:pk>', Formulario.as_view(), name='formulario'),
]

usuarios/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from .views import Perfilusuario, Criarusuario, Perfil, ChangeDone, Novo, \
    AutoCad, AutoCadDocumento, AutoCadEndereco, AutoCadContato, AutoCadMilitar, AutoCadDone, \
    GestUsuario, ConfirmUsuario, AllUsuario, \
    UpdateAutoCadPessoa, UpdateAutoCadContato, UpdateAutoCadDocumento, UpdateAutoCadEndereco, \
    UpdateAutoCadMilitar, \
    GestFuncao

app_name = 'usuarios'

urlpatterns = [
    path('login', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('autocad', Novo.as_view(), name='novo'),
    path('mudarsenha', auth_view.PasswordChangeView.as_view(success_url=reverse_lazy('usuarios:senhaalterada'),
                                                            template_name='perfilusuario.html'), name='mudarsenha'),
    path('mudarsenha/done', ChangeDone.as_view(), name='senhaalterada'),
    path('novo', Criarusuario.as_view(), name='criarusuario'),
    path('perfil/usuario/<int:pk>', Perfilusuario.as_view(), name='perfilusuario'),
    path('perfil/<int:pk>', Perfil.as_view(), name='perfil'),
    path('autocad/<int:pk>', AutoCad.as_view(), name='autocad'),
    path('autocad/contato', AutoCadContato.as_view(), name='autocadcontato'),
    path('autocad/documento', AutoCadDocumento.as_view(), name='autocaddocumento'),
    path('autocad/endereco', AutoCadEndereco.as_view(), name='autocadendereco'),
    path('autocad/militar', AutoCadMilitar.as_view(), name='autocadmilitar'),
    path('autocad/done', AutoCadDone.as_view(), name='autocaddone'),
    path('gestusuario', GestUsuario.as_view(), name='gestusuario'),
    path('confirmusuario/<int:pk>', ConfirmUsuario.as_view(), name='confirmusuario'),
    path('allusuario', AllUsuario.as_view(), name='allusuario'),
    path('autocad/update/pessoa/<int:pk>', UpdateAutoCadPessoa.as_view(), name='update_autocadpessoa'),
    path('autocad/update/contato/<int:pk>', UpdateAutoCadContato.as_view(), name='update_autocadcontato'),
    path('autocad/update/endereco/<int:pk>', UpdateAutoCadEndereco.as_view(), name='update_autocadendereco'),
    path('autocad/update/documento/<int:pk>', UpdateAutoCadDocumento.as_view(), name='update_autocaddocumento'),
    path('autocad/update/militar/<int:pk>', UpdateAutoCadMilitar.as_view(), name='update_autocadmilitar'),
    path('gestfuncao', GestFuncao.as_view(), name='gestfuncao'),
]

militares/views.py
from django.shortcuts import reverse
from django.views.generic import ListView, \
    CreateView, \
    DetailView, \
    UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Observacao, Militar, Atributos, Destino
from .forms import CriarMilitarForm, \
    UpdateObservacaoForm, \
    PerfilMilitarForm, \
    UpdateDestinoForm, \
    CriarDestinoForm
from pessoas.models import Pessoa
from usuarios.function_usuarios import troca_su
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa
import io
from datetime import datetime, timezone
from .function_militares import lista_transgre, define_pontos, define_atributos


class Fatosobservados(LoginRequiredMixin, ListView):
    template_name = "fatosobservados.html"
    model = Pessoa

    def get_context_data(self, **kwargs):
        context = super(Fatosobservados, self).get_context_data(**kwargs)
        pessoa = self.request.user.pessoas
        aux_s1 = self.request.user.pessoas.militar.unidade.acesso_s1.all()
        quadros = self.request.user.pessoas.militar.unidade.quadros.all()
        if (pessoa in quadros) or (pessoa in aux_s1):
            om_logada = self.request.user.pessoas.militar.unidade
            soldados = Militar.objects.filter(unidade=om_logada,
                                              pessoa__situacao="Ativo",
                                              posto_grad__icontains="Soldado").order_by('-posto_grad')
            cabos = Militar.objects.filter(unidade=om_logada,
                                           pessoa__situacao="Ativo",
                                           posto_grad__icontains="Cabo")
            context["soldados"] = soldados
            context["cabos"] = cabos
            return context


class Pesquisafatosobs(LoginRequiredMixin, ListView):
    template_name = "pesquisafatosobs.html"
    model = Militar

    def get_queryset(self):
        pesquisa = self.request.GET.get("query")
        pessoa = self.request.user.pessoas
        aux_s1 = self.request.user.pessoas.militar.unidade.acesso_s1.all()
        quadros = self.request.user.pessoas.militar.unidade.quadros.all()
        if pesquisa:
            if (pessoa in quadros) or (pessoa in aux_s1):
                om_logada = self.request.user.pessoas.militar.unidade
                object_list = self.model.objects.filter(pessoa__nome_completo__icontains=pesquisa,
                                                        unidade=om_logada,
                                                        pessoa__situacao="Ativo")
                return object_list
        else:
            return None


class Fatosobservadospessoa(LoginRequiredMixin, DetailView):
    template_name = "fatosobservadospessoa.html"
    model = Pessoa

    def get_context_data(self, **kwargs):
        context = super(Fatosobservadospessoa, self).get_context_data(**kwargs)
        observacoes = Observacao.objects.all()
        context["observacoes"] = observacoes
        return context


class Criarmilitar(LoginRequiredMixin, CreateView):
    template_name = "criarmilitar.html"
    model = Militar
    form_class = CriarMilitarForm

    def get_context_data(self, **kwargs):
        context = super(Criarmilitar, self).get_context_data(**kwargs)
        data = {'id': self.request.GET['novo_id']}
        pessoa = Pessoa.objects.get(id=data['id'])
        context["pessoa"] = pessoa
        return context

    def get_form_kwargs(self):
        kwargs = super(Criarmilitar, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        data = {'id': self.request.GET['novo_id']}
        form.instance.pessoa = Pessoa.objects.get(id=data['id'])
        form.instance.unidade = self.request.user.pessoas.militar.unidade
        form.save()
        id_mil = Militar.objects.last().id
        id_su = Militar.objects.last().subunidade.id
        troca_su(id_su, id_mil)
        return super().form_valid(form)

    def get_success_url(self):
        militar = Militar.objects.last()
        atrib = Atributos.objects.create(militar=militar)
        atrib.save()
        data = {'id': self.request.GET['novo_id']}
        pessoa = Pessoa.objects.get(id=data['id'])
        return reverse('pessoas:cadastropessoa', kwargs={"pk": pessoa.id})


class Criarobservacao(LoginRequiredMixin, CreateView):
    template_name = "criarobservacao.html"
    model = Observacao
    fields = ['tipo', 'relato_fato']

    def form_valid(self, form):
        militar = Militar.objects.get(id=self.request.user.pessoas.militar.id)
        arrolado = Militar.objects.get(id=self.request.GET.get("arrolado"))
        form.instance.participante = militar
        form.instance.arrolado = arrolado
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Criarobservacao, self).get_context_data(**kwargs)
        militar = Militar.objects.get(id=self.request.GET.get("arrolado"))
        context["militar"] = militar
        return context

    def get_success_url(self):
        observacao = Observacao.objects.all().last()
        observacao.nr_processo = int(observacao.id) + 1
        observacao.save()
        return reverse('militares:fatosobservadospessoa', kwargs={"pk": observacao.arrolado.pessoa.id})


class Updateobservacao(LoginRequiredMixin, UpdateView):
    template_name = "updateobservacao.html"
    model = Observacao
    form_class = UpdateObservacaoForm

    def get_context_data(self, **kwargs):
        context = super(Updateobservacao, self).get_context_data(**kwargs)
        context["lista"] = lista_transgre
        return context

    def get_form_kwargs(self):
        kwargs = super(Updateobservacao, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        id_obs = self.get_object().id
        asks = self.request.POST
        define_pontos(id_obs)
        define_atributos(id_obs, asks)
        observacao = Observacao.objects.get(id=id_obs)
        return reverse('militares:fatosobservadospessoa', kwargs={"pk": observacao.arrolado.pessoa.id})


class Perfilmilitar(LoginRequiredMixin, UpdateView):
    template_name = "perfilmilitar.html"
    model = Militar
    form_class = PerfilMilitarForm

    def form_valid(self, form):
        id_mil = self.get_object().id
        id_su = form.instance.subunidade.id
        form.save()
        troca_su(id_su, id_mil)
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(Perfilmilitar, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        if self.get_object().id == self.request.user.pessoas.militar.id:
            return reverse('usuarios:perfil', kwargs={"pk": self.request.user.pessoas.pk})
        else:
            return reverse('pessoas:cadastropessoa', kwargs={"pk": self.get_object().pessoas.pk})


# TODO: mapa da força
class Verdestino(LoginRequiredMixin, ListView):
    template_name = "destino.html"
    model = Militar

    def dispatch(self, request, *args, **kwargs):
        om_logada = request.user.pessoas.militar.unidade
        militares = Militar.objects.filter(unidade=om_logada, pessoa__situacao="Ativo")
        hoje = datetime.now(timezone.utc)
        for militar in militares:
            destinos = militar.destino.all()
            for destino in destinos:
                if destino.check_out:
                    if (hoje < destino.check_out) and (hoje > destino.check_in):
                        if destino.in_force and not militar.is_present:
                            pass
                        else:
                            destino.in_force = True
                            militar.is_present = False
                            destino.save()
                            militar.save()
                    else:
                        if not destino.in_force and militar.is_present:
                            pass
                        else:
                            destino.in_force = False
                            militar.is_present = True
                            destino.save()
                            militar.save()
                else:
                    if destino.in_force and not militar.is_present:
                        pass
                    else:
                        destino.in_force = True
                        militar.is_present = False
                        destino.save()
                        militar.save()
        return super(Verdestino, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Verdestino, self).get_context_data(**kwargs)
        pessoa = self.request.user.pessoas
        s1 = self.request.user.pessoas.militar.unidade.s1
        aux_s1 = self.request.user.pessoas.militar.unidade.acesso_s1.all()
        cmt_su = self.request.user.pessoas.militar.subunidade.cmt
        quadros_su = self.request.user.pessoas.militar.subunidade.quadros.all()
        if (pessoa == s1) or (pessoa in aux_s1):
            om_logada = self.request.user.pessoas.militar.unidade
            destinos = Destino.objects.filter(militar__unidade=om_logada,
                                              in_force=True,
                                              militar__pessoa__situacao="Ativo")
            context["destinos"] = destinos
            context["s1"] = s1
            context["aux_s1"] = aux_s1
            return context
        elif (pessoa == cmt_su) or (pessoa in quadros_su):
            su_logada = self.request.user.pessoas.militar.subunidade
            destinos = Destino.objects.filter(militar__subunidade=su_logada,
                                               in_force=True,

militares/templates/destino.html
{% extends 'base.html' %}
{% block titulo %}
Destinos da {{ request.user.pessoas.militar.subunidade }}
{% endblock %}
{% block head %}
    <style type="text/css">
        #bot {
            text-align: center;
        }
    </style>
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                    {% if request.user.pessoas == s1 or request.user.pessoas in aux_s1 %}
                        <h2>Destinos {{ request.user.pessoas.militar.unidade }}</h2>
                    {% else %}
                        <h2>Destinos {{ request.user.pessoas.militar.subunidade }}</h2>
                    {% endif %}
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                            {% if request.user.pessoas == s1 or request.user.pessoas in aux_s1 %}
                                <h2>{{ request.user.pessoas.militar.unidade }}</h2>
                            {% else %}
                                <h2>{{ request.user.pessoas.militar.subunidade }}</h2>
                            {% endif %}
                            </div>
                            <div class="bottom_list">
                                <div class="right_button">
                                    <a href="{% url 'militares:criardestino' %}">
                                        <button type="button" class="btn btn-primary btn-xs">Criar Destino
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th style="width: 10%">P/G</th>
                                                <th style="width: 10%">Militar</th>
                                                <th style="width: 10%">Início</th>
                                                <th style="width: 10%">Final</th>
                                                <th style="width: 50%">Motivo</th>
                                                <th style="width: 10%">Atualizar</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                    {% for destino in destinos %}
                                                            <tr>
                                                                <td>{{ destino.militar.posto_grad }}</td>
                                                                <td>{{ destino.militar.nome_guerra }}</td>
                                                                <td>{{ destino.check_in.day }}/{{ destino.check_in.month }}/{{ destino.check_in.year }} às {{ destino.check_in.time }}</td>
                                                                {% if destino.check_out %}
                                                                    <td>{{ destino.check_out.day }}/{{ destino.check_out.month }}/{{ destino.check_out.year }} às {{ destino.check_out.time }}</td>
                                                                {% else %}
                                                                    <td>Sem previsão de retorno</td>
                                                                {% endif %}
                                                                <td>{{ destino.motivo }}</td>
                                                                <td>
                                                                    <a href="{% url 'militares:updatedestino' destino.id %}">
                                                                        <button type="button" class="btn btn-success btn-xs">Atualizar
                                                                    </button></a>
                                                                </td>
                                                            </tr>
                                                    {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <br>
                                    <div id="bot">
                                        <a type="button" class="btn cur-p btn-secondary"
                                           href="{% url 'militares:mapa_forca' %}">Mapa da Força
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

militares/templates/fatosobservadospessoa.html
{% extends 'base.html' %}
{% block titulo %}
{% if pessoa.militar %}
Perfil de {{ pessoa.militar.nome_guerra }}
{% else %}
Perfil de {{ pessoa }}
{% endif %}
{% endblock %}
{% block head %}
    <style type="text/css">
        #bot {
            text-align: center;
        }
    </style>
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        {% if pessoa.militar %}
                        <h2>Perfil de {{ pessoa.militar.nome_guerra }}</h2>
                        {% else %}
                        <h2>Perfil de {{ pessoa }}</h2>
                        {% endif %}
                    </div>

                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                {% if pessoa.militar %}
                                <h2>Fatos Observados de {{ pessoa.militar.nome_guerra }}</h2>
                                {% else %}
                                <h2>Fatos Observados de {{ pessoa }}</h2>
                                {% endif %}
                            </div>
                            <div class="bottom_list">
                                <div class="bottom_block">
                                    <div class="float-left">
                                        <form method="get" action="{% url 'militares:criarobservacao' %}">
                                            <input type="hidden" name="arrolado" value="{{ pessoa.militar.id }}">
                                            <button type="submit" class="btn btn-primary btn-xs">
                                                <i class="fa fa-pencil-square-o"></i>Criar Novo Fato
                                            </button>
                                        </form>
                                    </div>

                                    <div class="float-right">
                                        <a href="{% url 'militares:fatosobservados' %}">
                                            <button type="button" class="btn btn-primary btn-xs">Voltar
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th style="width: 60%">Relato do Fato</th>
                                                <th style="width: 5%">Data</th>
                                                <th style="width: 10%">Solução</th>
                                                <th style="width: 5%">Dias</th>
                                                <th style="width: 10%">Atualizar</th>
                                                <th style="width: 10%">Gerar FATD</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for obs in observacoes %}
                                                {% if object == obs.arrolado.pessoa %}
                                                    {% if obs.tipo == 'negativa' %}
                                                        <tr class="table-danger">
                                                            <td>
                                                                <a>{{ obs.relato_fato }}</a>
                                                            </td>
                                                            <td>{{ obs.data.day }}/{{ obs.data.month }}/{{ obs.data.year }}</td>
                                                            <td>{{ obs.solucao }}</td>
                                                            {% if obs.dias %}
                                                                <td>{{ obs.dias }}</td>
                                                            {% else %}
                                                                <td>-</td>
                                                            {% endif %}
                                                            <td>
                                                                <a href="{% url 'militares:updateobservacao' obs.id %}"><button type="button" class="btn btn-success btn-xs">Atualizar
                                                                </button></a>
                                                            </td>

                                                            <td>
                                                                <a type="button" class="btn btn-danger btn-xs" href="{% url 'militares:fatd' obs.id %}">FATD
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    {% elif obs.tipo == 'positiva' %}
                                                        <tr class="table-info">
                                                            <td>
                                                                <a>{{ obs.relato_fato }}</a>
                                                            </td>
                                                            <td>{{ obs.data.day }}/{{ obs.data.month }}/{{ obs.data.year }}</td>
                                                            <td>{{ obs.solucao }}</td>
                                                            {% if obs.dias %}
                                                                <td>{{ obs.dias }}</td>
                                                            {% else %}
                                                                <td>-</td>
                                                            {% endif %}
                                                            <td>
                                                                <a href="{% url 'militares:updateobservacao' obs.id %}"><button type="button" class="btn btn-success btn-xs">Atualizar
                                                                </button></a>
                                                            </td>

                                                            <td>-</td>
                                                        </tr>
                                                    {% else %}
                                                        <tr class="table-warning">
                                                            <td>
                                                                <a>{{ obs.relato_fato }}</a>
                                                            </td>
                                                            <td>{{ obs.data.day }}/{{ obs.data.month }}/{{ obs.data.year }}</td>
                                                            <td>{{ obs.solucao }}</td>
                                                            {% if obs.dias %}
                                                                <td>{{ obs.dias }}</td>
                                                            {% else %}
                                                                <td>-</td>
                                                            {% endif %}
                                                            <td>
                                                                <a href="{% url 'militares:updateobservacao' obs.id %}"><button type="button" class="btn btn-success btn-xs">Atualizar
                                                                </button></a>
                                                            </td>

                                                            <td>-</td>
                                                        </tr>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <br>
                                    <div id="bot">
                                        <a type="button" class="btn cur-p btn-secondary"
                                           href="{% url 'militares:fdi' pessoa.militar.id %}">Ficha Disciplinar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}