Gest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    path('militares/', include('militares.urls', namespace='militares')),
    path('contatos/', include('contatos.urls', namespace='contatos')),
    path('documentos/', include('documentos.urls', namespace='documentos')),
    path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viaturas/urls.py
from django.urls import path
from .views import Viaturas, Updateviatura, Criarviatura, \
    Armamentos, Criararmamento, Updatearmamento, DashboardArmt, \
    Municoes, Criarmunicao, Updatemunicao, Criarconsumo, Criaralteracao

app_name = 'viaturas'

urlpatterns = [
    path('material/viatura', Viaturas.as_view(), name='viatura'),
    path('material/viatura/novo', Criarviatura.as_view(), name='criarviatura'),
    path('material/viatura/update/<int:pk>', Updateviatura.as_view(), name='updateviatura'),
    path('material/armamento', Armamentos.as_view(), name='armamento'),
    path('material/armamento/dash', DashboardArmt.as_view(), name='dash_armt'),
    path('material/armamento/novo', Criararmamento.as_view(), name='criararmamento'),
    path('material/armamento/update/<int:pk>', Updatearmamento.as_view(), name='updatearmamento'),
    path('material/municao', Municoes.as_view(), name='municao'),
    path('material/municao/novo', Criarmunicao.as_view(), name='criarmunicao'),
    path('material/municao/update/<int:pk>', Updatemunicao.as_view(), name='updatemunicao'),
    path('material/municao/consumo', Criarconsumo.as_view(), name='criarconsumo'),
    path('material/armamento/alteracao', Criaralteracao.as_view(), name='criaralteracao'),
]

viaturas/forms.py
from django.forms import ModelForm
from .models import Viatura, Armamento, Municao
from subunidades.models import Subunidade


class ViaturaForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(ViaturaForm, self).__init__(*args, **kwargs)
        unidade = user.pessoas.militar.unidade
        self.fields['subunidade'].queryset = Subunidade.objects.filter(OM=unidade)

    class Meta:
        model = Viatura
        exclude = ['unidade']


class ArmamentoForm(ModelForm):
    def __init__(self, user,  *args, **kwargs):
        super(ArmamentoForm, self).__init__(*args, **kwargs)
        unidade = user.pessoas.militar.unidade
        self.fields['subunidade'].queryset = Subunidade.objects.filter(OM=unidade)

    class Meta:
        model = Armamento
        exclude = ['unidade']


class MunicaoForm(ModelForm):
    class Meta:
        model = Municao
        exclude = ['unidade']

viaturas/views.py
from django.shortcuts import reverse
from django.db.models import Count
from django.views.generic import ListView, CreateView, UpdateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Viatura, Armamento, Municao, ConsumoMun, Alteracao
from .forms import ViaturaForm, ArmamentoForm, MunicaoForm
from quarteis.models import Quartel
from subunidades.models import Subunidade
from math import ceil


class Viaturas(LoginRequiredMixin, ListView):
    template_name = "viatura.html"
    model = Viatura

    def get_context_data(self, **kwargs):
        context = super(Viaturas, self).get_context_data(**kwargs)
        unidade_logada = self.request.user.pessoas.militar.unidade
        viaturas = Viatura.objects.filter(unidade=unidade_logada)
        context["viaturas"] = viaturas
        return context


class Criarviatura(LoginRequiredMixin, CreateView):
    template_name = "criarviatura.html"
    model = Viatura
    form_class = ViaturaForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoas.militar.unidade
        form.instance.unidade = unidade_logada
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(Criarviatura, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('viaturas:viatura')


class Updateviatura(LoginRequiredMixin, UpdateView):
    template_name = "updateviatura.html"
    model = Viatura
    form_class = ViaturaForm

    def get_form_kwargs(self):
        kwargs = super(Updateviatura, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('viaturas:viatura')


class Armamentos(LoginRequiredMixin, ListView):
    template_name = "armamento.html"
    model = Armamento

    def get_context_data(self, **kwargs):
        context = super(Armamentos, self).get_context_data(**kwargs)
        unidade_logada = self.request.user.pessoas.militar.unidade
        armamentos = Armamento.objects.filter(unidade=unidade_logada)
        context["armamentos"] = armamentos
        return context


class Criararmamento(LoginRequiredMixin, CreateView):
    template_name = "criararmamento.html"
    model = Armamento
    form_class = ArmamentoForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoas.militar.unidade
        form.instance.unidade = unidade_logada
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(Criararmamento, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('viaturas:armamento')


class Updatearmamento(LoginRequiredMixin, UpdateView):
    template_name = "updatearmamento.html"
    model = Armamento
    form_class = ArmamentoForm

    def get_form_kwargs(self):
        kwargs = super(Updatearmamento, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('viaturas:armamento')


class Municoes(LoginRequiredMixin, ListView):
    template_name = "municao.html"
    model = Armamento

    def get_context_data(self, **kwargs):
        context = super(Municoes, self).get_context_data(**kwargs)
        unidade_logada = self.request.user.pessoas.militar.unidade
        municoes = Municao.objects.filter(unidade=unidade_logada)
        context["municoes"] = municoes
        return context


class Criarmunicao(LoginRequiredMixin, CreateView):
    template_name = "criarmunicao.html"
    model = Municao
    form_class = MunicaoForm

    def form_valid(self, form):
        unidade_logada = self.request.user.pessoas.militar.unidade
        form.instance.unidade = unidade_logada
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('viaturas:municao')


class Updatemunicao(LoginRequiredMixin, UpdateView):
    template_name = "updatemunicao.html"
    model = Municao
    form_class = MunicaoForm

    def get_success_url(self):
        return reverse('viaturas:municao')


class Criarconsumo(LoginRequiredMixin, CreateView):
    template_name = "criarconsumo.html"
    model = ConsumoMun
    fields = ['atividade', 'quantidade', 'data']

    def form_valid(self, form):
        mun_id = self.request.GET['municao_id']
        municao = Municao.objects.get(id=mun_id)
        municao.quantidade -= form.instance.quantidade
        form.instance.municao = municao
        form.save()
        municao.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('viaturas:municao')


class Criaralteracao(LoginRequiredMixin, CreateView):
    template_name = "criaralteracao.html"
    model = Alteracao
    fields = ['disparos', 'situacao', 'alteracao', 'data']

    def form_valid(self, form):
        armt_id = self.request.GET['armt_id']
        armamento = Armamento.objects.get(id=armt_id)
        armamento.qtde_tiros += form.instance.disparos
        form.instance.armamento = armamento
        form.save()
        armamento.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('viaturas:armamento')


class DashboardArmt(LoginRequiredMixin, TemplateView):
    template_name = 'dash_armt.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardArmt, self).get_context_data(**kwargs)
        unidade = self.request.user.pessoas.militar.unidade.id
        quartel = Quartel.objects.get(id=unidade)
        bc = Subunidade.objects.get(nome="Bateria Comando")
        pbia = Subunidade.objects.get(nome="1ª Bateria de Obuses")
        sbia = Subunidade.objects.get(nome="2ª Bateria de Obuses")
        tbia = Subunidade.objects.get(nome="3ª Bateria de Morteiros")
        pst_su0 = Armamento.objects.filter(subunidade=bc, classificacao="Pistola 9mm")
        fz_su0 = Armamento.objects.filter(subunidade=bc, classificacao="Fuzil 7,62mm")
        fac_su0 = Armamento.objects.filter(subunidade=bc, classificacao="FAC")
        faca_su0 = Armamento.objects.filter(subunidade=bc, classificacao="Faca")
        epg_su0 = Armamento.objects.filter(subunidade=bc, classificacao="Espingarda 12")
        pst_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="Pistola 9mm")
        fz_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="Fuzil 7,62mm")
        fac_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="FAC")
        faca_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="Faca")
        dt_su1 = Armamento.objects.filter(subunidade=pbia,
                                          modelo="DISPOSITIVO DE TREINAMENTO DE ARTILHARIA")
        pcq_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="Metralhadora .50")
        fap_su1 = Armamento.objects.filter(subunidade=pbia, classificacao="FAP")
        psti_su2 = Armamento.objects.filter(subunidade=sbia,
                                            classificacao="Pistola 9mm", fabricante="IMBEL")
        pstb_su2 = Armamento.objects.filter(subunidade=sbia,
                                            classificacao="Pistola 9mm", fabricante="Beretta")
        fzfal_su2 = Armamento.objects.filter(subunidade=sbia, modelo="FAL M964")
        fzpfal_su2 = Armamento.objects.filter(subunidade=sbia, modelo="Para-FAL M964 A1 MD")
        fac_su2 = Armamento.objects.filter(subunidade=sbia, classificacao="FAC")
        faca_su2 = Armamento.objects.filter(subunidade=sbia, classificacao="Faca")
        epg_su2 = Armamento.objects.filter(subunidade=sbia, classificacao="Espingarda 12")
        dt_su2 = Armamento.objects.filter(subunidade=sbia,
                                          modelo="DISPOSITIVO DE TREINAMENTO DE ARTILHARIA")
        am_su2 = Armamento.objects.filter(subunidade=sbia,
                                          modelo="LANÇADOR DE GRANADA: AM-600")
        pst_su3 = Armamento.objects.filter(subunidade=tbia, classificacao="Pistola 9mm")
        fz_su3 = Armamento.objects.filter(subunidade=tbia, classificacao="Fuzil 7,62mm")
        fac_su3 = Armamento.objects.filter(subunidade=tbia, classificacao="FAC")
        faca_su3 = Armamento.objects.filter(subunidade=tbia, classificacao="Faca")

        context["pst_su0"] = pst_su0
        context["fz_su0"] = fz_su0
        context["fac_su0"] = fac_su0
        context["faca_su0"] = faca_su0
        context["epg_su0"] = epg_su0
        context["pst_su1"] = pst_su1
        context["fz_su1"] = fz_su1
        context["fac_su1"] = fac_su1
        context["faca_su1"] = faca_su1
        context["dt_su1"] = dt_su1
        context["pcq_su1"] = pcq_su1
        context["fap_su1"] = fap_su1
        context["psti_su2"] = psti_su2
        context["pstb_su2"] = pstb_su2
        context["fzfal_su2"] = fzfal_su2
        context["fzpfal_su2"] = fzpfal_su2
        context["fac_su2"] = fac_su2
        context["faca_su2"] = faca_su2
        context["epg_su2"] = epg_su2
        context["dt_su2"] = dt_su2
        context["am_su2"] = am_su2
        context["pst_su3"] = pst_su3
        context["fz_su3"] = fz_su3
        context["fac_su3"] = fac_su3
        context["faca_su3"] = faca_su3
        return context

viaturas/templates/armamento.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Armamento
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Armamentos</h2>
                    </div>

                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Armamentos</h2>

                            </div>
                            <div class="bottom_list">
                                <div class="right_button">
                                    <a href="{% url 'viaturas:criararmamento' %}">
                                        <button type="button" class="btn btn-primary btn-xs">
                                            <i class="fa fa-bomb"></i>Novo Armamento
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th>Classificação</th>
                                                <th>Modelo</th>
                                                <th>Número de Série</th>
                                                <th>Fabricante</th>
                                                <th>Tiros</th>
                                                <th>Situação</th>
                                                <th>Subunidade</th>
                                                {% if request.user.pessoas == request.user.pessoas.militar.unidade.s4 %}
                                                    <th>Atualizar</th>
                                                {% endif %}
                                                <th>Cadastrar Alteração</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for armamento in armamentos %}
                                                <tr>
                                                    <td>{{ armamento.classificacao }}</td>
                                                    <td>{{ armamento.modelo }}</td>
                                                    <td>{{ armamento.nr_serie }}</td>
                                                    <td>{{ armamento.fabricante }}</td>
                                                    <td>{{ armamento.qtde_tiros }}</td>
                                                    <td>{{ armamento.situacao }}</td>
                                                    <td>{{ armamento.subunidade }}</td>
                                                    {% if request.user.pessoas == request.user.pessoas.militar.unidade.s4 %}
                                                        <td>
                                                            <a href="{% url 'viaturas:updatearmamento' armamento.id %}">
                                                                <button type="button" class="btn cur-p btn-outline-info"><i class="fa fa-pencil"></i>
                                                            </button></a>
                                                        </td>
                                                    {% endif %}
                                                    <td>
                                                        <form method="get" action="{% url 'viaturas:criaralteracao' %}">
                                                            {{ form|crispy }}
                                                            <input name="armt_id" type="hidden" value="{{armamento.id}}">
                                                            <button class="btn cur-p btn-outline-info" type="submit">
                                                                <i class="fa fa-pencil"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

viaturas/templates/criaralteracao.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Alterações em Armamentos
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Armamentos</h2>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Alteração</h2>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <!-- column contact -->
                                <form method="post">
                                    {% csrf_token %}
                                    <fieldset class="form-group">
                                        <legend class="border-bottom mb-4">Cadastrar Alteração em Armamento</legend>
                                        {{ form|crispy }}
                                    </fieldset>
                                    <a class="btn btn-outline-secondary btn-lg float-left"
                                       href="{% url 'viaturas:armamento' %}" role="button">Voltar</a>
                                    <button class="btn btn-outline-secondary btn-lg float-right" type="submit">
                                        Cadastrar
                                    </button>
                                </form>
                                <!-- end column contact blog -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

viaturas/templates/municao.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Munição
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Munições</h2>
                    </div>

                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Munições</h2>

                            </div>
                            <div class="bottom_list">
                                <div class="right_button">
                                    <a href="{% url 'viaturas:criarmunicao' %}">
                                        <button type="button" class="btn btn-primary btn-xs">
                                            <i class="fa fa-fire"></i>Nova Munição
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th>Classificação</th>
                                                <th>Tipo</th>
                                                <th>Lote</th>
                                                <th>Vencimento</th>
                                                <th>Código Virola</th>
                                                <th>Quantidade</th>
                                                {% if request.user.pessoas == request.user.pessoas.militar.unidade.s4 %}
                                                    <th>Atualizar</th>
                                                {% endif %}
                                                <th>Registrar Consumo</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for municao in municoes %}
                                                <tr>
                                                    <td>{{ municao.classificacao }}</td>
                                                    <td>{{ municao.tipo }}</td>
                                                    <td>{{ municao.lote }}</td>
                                                    <td>{{ municao.vencimento }}</td>
                                                    <td>{{ municao.codigo_virola }}</td>
                                                    <td>{{ municao.quantidade }}</td>
                                                    {% if request.user.pessoas == request.user.pessoas.militar.unidade.s4 %}
                                                        <td>
                                                            <a href="{% url 'viaturas:updatemunicao' municao.id %}">
                                                                <button type="button" class="btn cur-p btn-outline-info"><i class="fa fa-pencil"></i>
                                                            </button></a>
                                                        </td>
                                                    {% endif %}
                                                    <td>
                                                        <form method="get" action="{% url 'viaturas:criarconsumo' %}">
                                                            {{ form|crispy }}
                                                            <input name="municao_id" type="hidden" value="{{municao.id}}">
                                                            <button class="btn cur-p btn-outline-info" type="submit">
                                                                <i class="fa fa-pencil"></i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

viaturas/templates/viatura.html
{% extends 'base.html' %}
{% block titulo %}
Viaturas
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Viaturas</h2>
                    </div>

                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Viaturas</h2>

                            </div>
                            <div class="bottom_list">
                                <div class="right_button">
                                    <a href="{% url 'viaturas:criarviatura' %}">
                                        <button type="button" class="btn btn-primary btn-xs">
                                            <i class="fa fa-car"></i>Nova Viatura
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th style="width: 4%">Odômetro</th>
                                                <th>Nr Patrimônio</th>
                                                <th>Marca</th>
                                                <th>Modelo</th>
                                                <th>Combustível</th>
                                                <th>Consumo</th>
                                                <th>Capacidade Tanque</th>
                                                <th>Qtde Passageiros</th>
                                                <th>Situação</th>
                                                <th>Atualizar</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for viatura in viaturas %}
                                                <tr>
                                                    <td>{{ viatura.odometro }}</td>
                                                    <td>{{ viatura.patrimonio }}</td>
                                                    <td>{{ viatura.marca }}</td>
                                                    <td>{{ viatura.modelo }}</td>
                                                    <td>{{ viatura.combustivel }}</td>
                                                    <td>{{ viatura.consumo_plan }}</td>
                                                    <td>{{ viatura.capacidade_combustivel }}</td>
                                                    <td>{{ viatura.capacidade_passageiro }}</td>
                                                    <td>{{ viatura.situacao }}</td>
                                                    <td>
                                                        <a href="{% url 'viaturas:updateviatura' viatura.id %}">
                                                            <button type="button" class="btn btn-success btn-xs">Atualizar
                                                        </button></a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}