Gest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    path('militares/', include('militares.urls', namespace='militares')),
    path('contatos/', include('contatos.urls', namespace='contatos')),
    path('documentos/', include('documentos.urls', namespace='documentos')),
    path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pessoas/urls.py
from django.urls import path
from .views import Cadastro, \
    Cadastropessoa, \
    Criarpessoa, \
    Delete, \
    Perfilpessoa, \
    ListConscrito, \
    ReadConscrito, \
    Formulario, \
    Pesquisacadastro

app_name = 'pessoas'

urlpatterns = [
    path('cadastro', Cadastro.as_view(), name='cadastro'),
    path('cadastro/pesquisa', Pesquisacadastro.as_view(), name='pesquisacadastro'),
    path('cadastro/<int:pk>', Cadastropessoa.as_view(), name='cadastropessoa'),
    path('cadastro/novo', Criarpessoa.as_view(), name='criarpessoa'),
    path('cadastro/delete/<int:pk>', Delete.as_view(), name='delete'),
    path('perfil/<int:pk>', Perfilpessoa.as_view(), name='perfilpessoa'),
    path('cadastro/listconscrito', ListConscrito.as_view(), name='listconscrito'),
    path('cadastro/readconscrito/<int:pk>', ReadConscrito.as_view(), name='readconscrito'),
    path('cadastro/formulario/<int:pk>', Formulario.as_view(), name='formulario'),
]

questionarios/urls.py
from django.urls import path
from .views import Createquestionarioum, \
    Createquestionariodois, \
    Createquestionariotres, \
    Updatequestionarioum, \
    Updatequestionariodois, \
    Updatequestionariotres, \
    Updateum, \
    Updatedois, \
    Updatetres

app_name = 'questionarios'

urlpatterns = [
    path('create/questionario1', Createquestionarioum.as_view(), name='create_questionario_um'),
    path('create/questionario2', Createquestionariodois.as_view(), name='create_questionario_dois'),
    path('create/questionario3', Createquestionariotres.as_view(), name='create_questionario_tres'),
    path('update/questionario1/<int:pk>', Updatequestionarioum.as_view(), name='update_questionario_um'),
    path('update/questionario2/<int:pk>', Updatequestionariodois.as_view(), name='update_questionario_dois'),
    path('update/questionario3/<int:pk>', Updatequestionariotres.as_view(), name='update_questionario_tres'),
    path('update/um/<int:pk>', Updateum.as_view(), name='update_um'),
    path('update/dois/<int:pk>', Updatedois.as_view(), name='update_dois'),
    path('update/tres/<int:pk>', Updatetres.as_view(), name='update_tres')
]

usuarios/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from .views import Perfilusuario, Criarusuario, Perfil, ChangeDone, Novo, \
    AutoCad, AutoCadDocumento, AutoCadEndereco, AutoCadContato, AutoCadMilitar, AutoCadDone, \
    GestUsuario, ConfirmUsuario, AllUsuario, \
    UpdateAutoCadPessoa, UpdateAutoCadContato, UpdateAutoCadDocumento, UpdateAutoCadEndereco, \
    UpdateAutoCadMilitar, \
    GestFuncao

app_name = 'usuarios'

urlpatterns = [
    path('login', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('autocad', Novo.as_view(), name='novo'),
    path('mudarsenha', auth_view.PasswordChangeView.as_view(success_url=reverse_lazy('usuarios:senhaalterada'),
                                                            template_name='perfilusuario.html'), name='mudarsenha'),
    path('mudarsenha/done', ChangeDone.as_view(), name='senhaalterada'),
    path('novo', Criarusuario.as_view(), name='criarusuario'),
    path('perfil/usuario/<int:pk>', Perfilusuario.as_view(), name='perfilusuario'),
    path('perfil/<int:pk>', Perfil.as_view(), name='perfil'),
    path('autocad/<int:pk>', AutoCad.as_view(), name='autocad'),
    path('autocad/contato', AutoCadContato.as_view(), name='autocadcontato'),
    path('autocad/documento', AutoCadDocumento.as_view(), name='autocaddocumento'),
    path('autocad/endereco', AutoCadEndereco.as_view(), name='autocadendereco'),
    path('autocad/militar', AutoCadMilitar.as_view(), name='autocadmilitar'),
    path('autocad/done', AutoCadDone.as_view(), name='autocaddone'),
    path('gestusuario', GestUsuario.as_view(), name='gestusuario'),
    path('confirmusuario/<int:pk>', ConfirmUsuario.as_view(), name='confirmusuario'),
    path('allusuario', AllUsuario.as_view(), name='allusuario'),
    path('autocad/update/pessoa/<int:pk>', UpdateAutoCadPessoa.as_view(), name='update_autocadpessoa'),
    path('autocad/update/contato/<int:pk>', UpdateAutoCadContato.as_view(), name='update_autocadcontato'),
    path('autocad/update/endereco/<int:pk>', UpdateAutoCadEndereco.as_view(), name='update_autocadendereco'),
    path('autocad/update/documento/<int:pk>', UpdateAutoCadDocumento.as_view(), name='update_autocaddocumento'),
    path('autocad/update/militar/<int:pk>', UpdateAutoCadMilitar.as_view(), name='update_autocadmilitar'),
    path('gestfuncao', GestFuncao.as_view(), name='gestfuncao'),
]

pessoas/models.py
from django.db import models
from usuarios.models import Usuario

LISTA_SITUACAO = (
    ("Pré-Cadastro", "Pendente de Homologação"),
    ("Ativo", "Ativo"),
    ("Arquivo", "Excluído do Efetivo")
)

LISTA_SANGUE = (
    ("O", "O"),
    ("A", "A"),
    ("B", "B"),
    ("AB", "AB"),
)

LISTA_FATORRH = (
    ("+", "Positivo"),
    ("-", "Negativo"),
)

LISTA_ESCOLARIDADE = (
    ("Analfabeto", "Analfabeto"),
    ("Fundamental Incompleto", "Fundamental Incompleto"),
    ("Fundamental Completo", "Fundamental Completo"),
    ("Médio Incompleto", "Médio Incompleto"),
    ("Médio Completo", "Médio Completo"),
    ("Superior Incompleto", "Superior Incompleto"),
    ("Superior Completo", "Superior Completo"),
    ("Pós-Graduação", "Pós-Graduação"),
    ("Mestrado", "Mestrado"),
    ("Doutorado", "Doutorado"),
)


class Pessoa(models.Model):
    nome_completo = models.CharField(max_length=250)
    data_nasc = models.DateField()
    foto = models.ImageField(upload_to='fotos', blank=True, null=True)
    nome_pai = models.CharField(max_length=250, blank=True, null=True)
    nome_mae = models.CharField(max_length=250, blank=True, null=True)
    tipo_sanguineo = models.CharField(
        "Tipo Sanguíneo",
        max_length=2,
        choices=LISTA_SANGUE,
        blank=True, null=True
    )
    fator_rh = models.CharField(
        "Fator RH",
        max_length=8,
        choices=LISTA_FATORRH,
        blank=True, null=True
    )
    peso = models.IntegerField(default=70)
    altura = models.DecimalField(max_digits=3, decimal_places=2, default=1.70)
    situacao = models.CharField(
        max_length=30,
        choices=LISTA_SITUACAO,
        default="Pré-Cadastro",
    )
    escolaridade = models.CharField(
        max_length=60,
        choices=LISTA_ESCOLARIDADE,
        default="Fundamental Incompleto",
    )
    religiao = models.CharField(max_length=100, default='Não declarado')
    usuario = models.OneToOneField(Usuario, related_name="pessoas", on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        permissions = (
            ('acesso', 'Usuario pode alterar'),
        )

    def __str__(self):
        return self.nome_completo


class Banco(models.Model):
    nome = models.CharField("Nome do Banco", max_length=70, null=True, blank=True)
    agencia = models.CharField("Agência", max_length=30, null=True, blank=True)
    conta = models.CharField("Conta Corrente", max_length=50, null=True, blank=True)
    pessoa = models.ForeignKey(Pessoa, related_name="banco", on_delete=models.PROTECT, verbose_name="Titular")

    def __str__(self):
        return self.pessoa.nome_completo

pessoas/views.py
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import Pessoa
from militares.views import Render
from militares.models import Militar
from questionarios.models import RelatorioCS
import locale
from datetime import datetime
from math import ceil


# TODO: Verificar e testar tudão
class Cadastro(LoginRequiredMixin, ListView):
    template_name = "cadastro.html"
    model = Pessoa

    def get_context_data(self, **kwargs):
        context = super(Cadastro, self).get_context_data(**kwargs)
        pessoa = self.request.user.pessoas
        s1 = self.request.user.pessoas.militar.unidade.s1
        aux_s1 = self.request.user.pessoas.militar.unidade.acesso_s1.all()
        cmt_su = self.request.user.pessoas.militar.subunidade.cmt
        sgte = self.request.user.pessoas.militar.subunidade.sgte
        aux_sgte = self.request.user.pessoas.militar.subunidade.acesso_sgte.all()
        if (pessoa == s1) or (pessoa in aux_s1):
            om_logada = self.request.user.pessoas.militar.unidade
            militares = Militar.objects.filter(unidade=om_logada, pessoa__situacao="Ativo").order_by("-posto_grad")
            context["militares"] = militares
            return context
        if (pessoa == cmt_su) or (pessoa == sgte) or (pessoa in aux_sgte):
            su_logada = self.request.user.pessoas.militar.subunidade
            militares = Militar.objects.filter(subunidade=su_logada, pessoa__situacao="Ativo").order_by("-posto_grad")
            context["militares"] = militares
            return context


class Pesquisacadastro(LoginRequiredMixin, ListView):
    template_name = "pesquisacadastro.html"
    model = Militar

    def get_queryset(self):
        pesquisa = self.request.GET.get("query")
        pessoa = self.request.user.pessoas
        s1 = self.request.user.pessoas.militar.unidade.s1
        aux_s1 = self.request.user.pessoas.militar.unidade.acesso_s1.all()
        cmt_su = self.request.user.pessoas.militar.subunidade.cmt
        sgte = self.request.user.pessoas.militar.subunidade.sgte
        aux_sgte = self.request.user.pessoas.militar.subunidade.acesso_sgte.all()
        if pesquisa:
            if (pessoa == s1) or (pessoa in aux_s1):
                om_logada = self.request.user.pessoas.militar.unidade
                object_list = self.model.objects.filter(pessoa__nome_completo__icontains=pesquisa,
                                                        unidade=om_logada,
                                                        pessoa__situacao="Ativo")
                return object_list
            if (pessoa == cmt_su) or (pessoa == sgte) or (pessoa in aux_sgte):
                su_logada = self.request.user.pessoas.militar.subunidade
                object_list = self.model.objects.filter(pessoa__nome_completo__icontains=pesquisa,
                                                        subunidade=su_logada,
                                                        pessoa__situacao="Ativo")
                return object_list
        else:
            return None


class Cadastropessoa(LoginRequiredMixin, DetailView):
    template_name = "cadastropessoa.html"
    model = Pessoa


class Criarpessoa(LoginRequiredMixin, CreateView):
    template_name = "criarpessoa.html"
    model = Pessoa
    fields = ['nome_completo', 'data_nasc', 'foto', 'nome_pai', 'nome_mae', 'peso', 'fator_rh', 'tipo_sanguineo',
              'altura', 'escolaridade', 'religiao']

    def form_valid(self, form):
        form.instance.situacao = "Ativo"
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        pessoa = Pessoa.objects.all().last()
        return reverse('pessoas:cadastropessoa', kwargs={"pk": pessoa.id})


class Delete(LoginRequiredMixin, UpdateView):
    template_name = "delete.html"
    model = Pessoa
    fields = []

    def form_valid(self, form):
        form.instance.situacao = "Arquivo"
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('pessoas:cadastro')


class Perfilpessoa(LoginRequiredMixin, UpdateView):
    template_name = "perfilpessoa.html"
    model = Pessoa
    fields = ['nome_completo', 'data_nasc', 'foto', 'nome_pai', 'nome_mae', 'peso', 'fator_rh', 'tipo_sanguineo',
              'altura', 'escolaridade', 'religiao']

    def get_success_url(self):
        if self.get_object().id == self.request.user.pessoas.id:
            return reverse('usuarios:perfil', kwargs={"pk": self.request.user.pessoas.pk})
        else:
            return reverse('pessoas:cadastropessoa', kwargs={"pk": self.get_object().pk})


class ListConscrito(LoginRequiredMixin, ListView):
    template_name = "list_conscrito.html"
    model = Pessoa

    def get_context_data(self, **kwargs):
        context = super(ListConscrito, self).get_context_data(**kwargs)
        pessoa = self.request.user.pessoas
        quadros = self.request.user.pessoas.militar.unidade.quadros.all()
        if pessoa == quadros:
            om_logada = self.request.user.pessoas.militar.unidade
            c = Militar.objects.filter(unidade=om_logada,
                                       posto_grad='Conscrito',
                                       pessoa__situacao="Pré-Cadastro")
            conscritos = c.order_by('-atributos__ranking_inicial')
            context["conscritos"] = conscritos
            return context


class ReadConscrito(LoginRequiredMixin, UpdateView):
    template_name = 'read_conscrito.html'
    model = RelatorioCS
    fields = ['obs_entrevistador']

    def form_valid(self, form):
        militar = Militar.objects.get(id=self.request.user.pessoas.militar.id)
        relatorio = form.save(commit=False)
        relatorio.entrevistador = militar
        relatorio.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ReadConscrito, self).get_context_data(**kwargs)
        pessoa = Pessoa.objects.get(id=self.object.pessoa.id)
        ri = pessoa.militar.atributos.ranking_inicial
        numero = ceil(ri/3)
        context["numero"] = numero
        return context

    def get_success_url(self):
        return reverse('pessoas:listconscrito')


class Formulario(DetailView):
    template_name = "formulario_cs.html"
    model = Pessoa

    def get(self, request, *args, **kwargs):
        locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')
        pessoa = Pessoa.objects.get(id=self.kwargs['pk'])
        hoje = datetime.now()
        data = hoje.strftime("%d de %B de %Y")
        params = {
            'pessoa': pessoa,
            'hoje': hoje,
            'data': data,
            'request': request,
        }
        return Render.render('formulario_cs.html', params, f'formulario_{pessoa.id}')

pessoas/templates/cadastro.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Pessoal
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Cadastro do Pessoal</h2>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Militares do {{ request.user.pessoas.militar.unidade.abreviatura }}</h2>
                            </div>
                            <div class="bottom_list">
                                <form method="get" action="{% url 'pessoas:pesquisacadastro' %}"
                                      class="pull-right position search_inbox">
                                    <div class="input-append">
                                        <input type="text" class="sr-input" value="{{ request.GET.query }}"
                                               placeholder="Pesquisar..." name="query">
                                        <button class="btn sr-btn" type="submit"><i class="fa fa-search"></i></button>
                                    </div>
                                </form>
                                <div class="left_button">
                                    <a href="{% url 'pessoas:criarpessoa' %}">
                                        <button type="button" class="btn btn-primary btn-xs">
                                            <i class="fa fa-male"></i><i class="fa fa-female"></i>Criar Novo
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <!-- column contact -->
                                {% for militar in militares %}
                                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 profile_details margin_bottom_30">
                                        <div class="contact_blog">
                                            <h4 class="brief">{{ militar.qualificacao }}</h4>
                                            <div class="contact_inner">
                                                <div class="left">
                                                    <h3>{{ militar.nome_guerra }}</h3>
                                                    <p><strong>Posto/Grad: </strong>{{ militar.posto_grad }}</p>
                                                    <ul class="list-unstyled">
                                                        <li><i class="fa fa-envelope-o"></i> : {{ militar.pessoa.contato.email }}</li>
                                                        <li><i class="fa fa-phone"></i> : {{ militar.pessoa.contato.celular }}</li>
                                                        <li><i class="fa fa-tag"></i> : {{ militar.identidade }}</li>
                                                    </ul>
                                                </div>
                                                <div class="right">
                                                    <div class="profile_contacts">
                                                    {% if militar.pessoa.foto %}
                                                        <img class="img-responsive" src="{{ militar.pessoa.foto.url }}" alt="#"/>
                                                    {% else %}
                                                        <img class="img-responsive" src="{% static 'images/sem_img.png' %}" alt="#"/>
                                                    {% endif %}

                                                    </div>
                                                </div>
                                                <div class="bottom_list">
                                                    <div class="right_button">
                                                        <a href="{% url 'pessoas:delete' militar.pessoa.id %}">
                                                            <button type="button" class="btn cur-p btn-danger">
                                                                <i class="fa fa-eraser"></i>Deletar</button></a>
                                                        <a href="{% url 'pessoas:cadastropessoa' militar.pessoa.id %}">
                                                            <button type="button" class="btn btn-primary btn-xs">
                                                                <i class="fa fa-user"> </i>Ver Perfil</button></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <!-- end column contact blog -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

pessoas/templates/criarpessoa.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Pessoal
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Cadastro do Pessoal</h2>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Novo cadastro</h2>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <!-- column contact -->
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <fieldset class="form-group">
                                        <legend class="border-bottom mb-4">Cadastrar Dados Pessoais</legend>
                                        {{ form|crispy }}
                                    </fieldset>
                                    <a class="btn btn-outline-secondary btn-lg float-left"
                                       href="{% url 'pessoas:cadastro' %}" role="button">Voltar</a>
                                    <button class="btn btn-outline-secondary btn-lg float-right" type="submit">
                                        Cadastrar
                                    </button>
                                </form>
                                <!-- end column contact blog -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}

pessoas/templates/list_conscrito.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block titulo %}
Conscritos
{% endblock %}
{% block main %}

{% include 'sidebar.html' %}
<div id="content">
    {% include 'topbar.html' %}
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Conscritos</h2>
                    </div>

                </div>
            </div>
            <!-- row -->
            <div class="row column1">
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="heading1 margin_0">
                                <h2>Gestão de Conscritos</h2>
                            </div>
                        </div>
                        <div class="full price_table padding_infor_info">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive-sm">
                                        <table class="table table-striped projects">
                                            <thead class="thead-dark">
                                            <tr>
                                                <th style="width: 20%">Nome Completo</th>
                                                <th style="width: 5%">Sugestão</th>
                                                <th style="width: 10%">Ver Entrevista</th>
                                                <th style="width: 10%">Realizar Observação</th>
                                                <th style="width: 10%">Entrevista</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for conscrito in conscritos %}
                                                    <tr>
                                                        <td>{{ conscrito.pessoa.nome_completo }}</td>
                                                        <td>{{ conscrito.pessoa.relatorio_cs.sugestao }}</td>
                                                        <td>
                                                            {% if conscrito.pessoa.questionario_um %}
                                                            <div class="button_block"><a href="{% url 'questionarios:update_um' conscrito.pessoa.questionario_um.id %}">
                                                                <button class="btn cur-p btn-dark">Questionário 1</button>
                                                            </a></div><br>
                                                            {% endif %}
                                                            {% if conscrito.pessoa.questionario_dois %}
                                                            <div class="button_block"><a href="{% url 'questionarios:update_dois' conscrito.pessoa.questionario_dois.id %}">
                                                                <button class="btn cur-p btn-dark">Questionário 2</button>
                                                            </a></div><br>
                                                            {% endif %}
                                                            {% if conscrito.pessoa.questionario_tres %}
                                                            <div class="button_block"><a href="{% url 'questionarios:update_tres' conscrito.pessoa.questionario_tres.id %}">
                                                                <button class="btn cur-p btn-dark">Questionário 3</button>
                                                            </a></div>
                                                            {% endif %}
                                                        </td>
                                                        <td>
                                                            {% if conscrito.pessoa.relatorio_cs %}
                                                            <div class="button_block"><a href="{% url 'pessoas:readconscrito' conscrito.pessoa.relatorio_cs.id %}">
                                                                <button class="btn cur-p btn-dark"><i class="fa fa-pencil-square-o yellow_color"></i></button>
                                                            </a></div>
                                                            {% endif %}
                                                        </td>
                                                        <td>
                                                            <div class="button_block"><a href="{% url 'pessoas:formulario' conscrito.pessoa.id %}">
                                                                <button class="btn cur-p btn-dark"><i class="fa fa-file-o yellow_color"></i> Baixar</button>
                                                            </a></div>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
        {% include 'footer.html' %}
    </div>
</div>

{% endblock %}