Gest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import Homepage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('', Homepage.as_view(), name='homepage'),
    path('pessoas/', include('pessoas.urls', namespace='pessoas')),
    path('militares/', include('militares.urls', namespace='militares')),
    path('contatos/', include('contatos.urls', namespace='contatos')),
    path('documentos/', include('documentos.urls', namespace='documentos')),
    path('enderecos/', include('enderecos.urls', namespace='enderecos')),
    path('viaturas/', include('viaturas.urls', namespace='viaturas')),
    path('questionarios/', include('questionarios.urls', namespace='questionarios')),
    path('quarteis/', include('quarteis.urls', namespace='quarteis')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pessoas/urls.py
from django.urls import path
from .views import Cadastro, \
    Cadastropessoa, \
    Criarpessoa, \
    Delete, \
    Perfilpessoa, \
    ListConscrito, \
    ReadConscrito, \
    Formulario, \
    Pesquisacadastro

app_name = 'pessoas'

urlpatterns = [
    path('cadastro', Cadastro.as_view(), name='cadastro'),
    path('cadastro/pesquisa', Pesquisacadastro.as_view(), name='pesquisacadastro'),
    path('cadastro/<int:pk>', Cadastropessoa.as_view(), name='cadastropessoa'),
    path('cadastro/novo', Criarpessoa.as_view(), name='criarpessoa'),
    path('cadastro/delete/<int:pk>', Delete.as_view(), name='delete'),
    path('perfil/<int:pk>', Perfilpessoa.as_view(), name='perfilpessoa'),
    path('cadastro/listconscrito', ListConscrito.as_view(), name='listconscrito'),
    path('cadastro/readconscrito/<int:pk>', ReadConscrito.as_view(), name='readconscrito'),
    path('cadastro/formulario/<int:pk>', Formulario.as_view(), name='formulario'),
]

quarteis/urls.py
from django.urls import path
from .views import create_dados, create_armt

app_name = 'quarteis'

urlpatterns = [
    path('dados_novo/', create_dados, name='create_dados'),
    path('armt_novo/', create_armt, name='create_armt'),
]

usuarios/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from .views import Perfilusuario, Criarusuario, Perfil, ChangeDone, Novo, \
    AutoCad, AutoCadDocumento, AutoCadEndereco, AutoCadContato, AutoCadMilitar, AutoCadDone, \
    GestUsuario, ConfirmUsuario, AllUsuario, \
    UpdateAutoCadPessoa, UpdateAutoCadContato, UpdateAutoCadDocumento, UpdateAutoCadEndereco, \
    UpdateAutoCadMilitar, \
    GestFuncao

app_name = 'usuarios'

urlpatterns = [
    path('login', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('autocad', Novo.as_view(), name='novo'),
    path('mudarsenha', auth_view.PasswordChangeView.as_view(success_url=reverse_lazy('usuarios:senhaalterada'),
                                                            template_name='perfilusuario.html'), name='mudarsenha'),
    path('mudarsenha/done', ChangeDone.as_view(), name='senhaalterada'),
    path('novo', Criarusuario.as_view(), name='criarusuario'),
    path('perfil/usuario/<int:pk>', Perfilusuario.as_view(), name='perfilusuario'),
    path('perfil/<int:pk>', Perfil.as_view(), name='perfil'),
    path('autocad/<int:pk>', AutoCad.as_view(), name='autocad'),
    path('autocad/contato', AutoCadContato.as_view(), name='autocadcontato'),
    path('autocad/documento', AutoCadDocumento.as_view(), name='autocaddocumento'),
    path('autocad/endereco', AutoCadEndereco.as_view(), name='autocadendereco'),
    path('autocad/militar', AutoCadMilitar.as_view(), name='autocadmilitar'),
    path('autocad/done', AutoCadDone.as_view(), name='autocaddone'),
    path('gestusuario', GestUsuario.as_view(), name='gestusuario'),
    path('confirmusuario/<int:pk>', ConfirmUsuario.as_view(), name='confirmusuario'),
    path('allusuario', AllUsuario.as_view(), name='allusuario'),
    path('autocad/update/pessoa/<int:pk>', UpdateAutoCadPessoa.as_view(), name='update_autocadpessoa'),
    path('autocad/update/contato/<int:pk>', UpdateAutoCadContato.as_view(), name='update_autocadcontato'),
    path('autocad/update/endereco/<int:pk>', UpdateAutoCadEndereco.as_view(), name='update_autocadendereco'),
    path('autocad/update/documento/<int:pk>', UpdateAutoCadDocumento.as_view(), name='update_autocaddocumento'),
    path('autocad/update/militar/<int:pk>', UpdateAutoCadMilitar.as_view(), name='update_autocadmilitar'),
    path('gestfuncao', GestFuncao.as_view(), name='gestfuncao'),
]

viaturas/urls.py
from django.urls import path
from .views import Viaturas, Updateviatura, Criarviatura, \
    Armamentos, Criararmamento, Updatearmamento, DashboardArmt, \
    Municoes, Criarmunicao, Updatemunicao, Criarconsumo, Criaralteracao

app_name = 'viaturas'

urlpatterns = [
    path('material/viatura', Viaturas.as_view(), name='viatura'),
    path('material/viatura/novo', Criarviatura.as_view(), name='criarviatura'),
    path('material/viatura/update/<int:pk>', Updateviatura.as_view(), name='updateviatura'),
    path('material/armamento', Armamentos.as_view(), name='armamento'),
    path('material/armamento/dash', DashboardArmt.as_view(), name='dash_armt'),
    path('material/armamento/novo', Criararmamento.as_view(), name='criararmamento'),
    path('material/armamento/update/<int:pk>', Updatearmamento.as_view(), name='updatearmamento'),
    path('material/municao', Municoes.as_view(), name='municao'),
    path('material/municao/novo', Criarmunicao.as_view(), name='criarmunicao'),
    path('material/municao/update/<int:pk>', Updatemunicao.as_view(), name='updatemunicao'),
    path('material/municao/consumo', Criarconsumo.as_view(), name='criarconsumo'),
    path('material/armamento/alteracao', Criaralteracao.as_view(), name='criaralteracao'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>
       {% block titulo %}{% endblock %}
    </title>
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/png" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <link rel="stylesheet" href="{% static 'css/colors.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'js/semantic.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" />
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body class="inner_page invoice_page">
    <div class="full_container">
        <div class="inner_container">
            {% block main %}
            {% endblock %}
        </div>
        {% block modal %}
        {% endblock %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/funcoes-ajax.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/animate.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/analyser.js' %}"></script>
    <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
    <script>
         var ps = new PerfectScrollbar('#sidebar');
    </script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/semantic.min.js' %}"></script>
</body>
</html>

templates/footer.html
    <div class="container-fluid">
        <div class="footer">
            <p>Copyright ©23 Designed by Carlos Artur. All rights reserved.</p>
        </div>
    </div>

templates/sidebar.html
{% load static %}
    <nav id="sidebar">
        <div class="sidebar_blog_1">
            <div class="sidebar-header">
                <div class="logo_section">
                    <a href="#"><img class="logo_icon img-responsive" src="{{ user.pessoas.militar.unidade.logo.url }}" alt="#" /></a>
                </div>
            </div>
            <div class="sidebar_user_info">
                <div class="icon_setting"></div>
                <div class="user_profle_side">
                    <div class="user_img">
                        {% if user.pessoas.foto %}
                            <img class="img-responsive" src="{{ user.pessoas.foto.url }}" alt="#" />
                        {% else %}
                            <img class="img-responsive" src="{% static 'images/sem_img.png' %}" alt="#"/>
                        {% endif %}
                    </div>
                    <div class="user_info">
                        {% if user.pessoas.militar %}
                        <h6>{{ user.pessoas.militar.nome_guerra }}</h6>
                        {% else %}
                        <h6>{{ user.pessoas.nome_completo }}</h6>
                        {% endif %}
                        <p><span class="online_animation"></span> Online</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar_blog_2">
            <h4>Conteúdo Geral</h4>
            <ul class="list-unstyled components">
                {% if request.user.pessoas == request.user.pessoas.militar.unidade.s1 or request.user.pessoas == request.user.pessoas.militar.subunidade.cmt or request.user.pessoas == request.user.pessoas.militar.subunidade.sgte %}
                    <li>
                        <a href="#usuarios" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="fa fa-users green_color"></i> <span>Usuários</span></a>
                        <ul class="collapse list-unstyled" id="usuarios">
                            <li><a href="{% url 'usuarios:gestusuario' %}">> <span>Novos Usuários</span></a></li>
                            <li><a href="{% url 'usuarios:allusuario' %}">> <span>Todos Usuários</span></a></li>
                            <li><a href="{% url 'usuarios:gestfuncao' %}">> <span>Funções e Acessos</span></a></li>
                        </ul>
                    </li>
                {% endif %}
                {% if request.user.pessoas in request.user.pessoas.militar.unidade.quadros.all %}
                    <li>
                        <a href="#pessoal" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="fa fa-tags yellow_color"></i> <span>Pessoal</span></a>
                        <ul class="collapse list-unstyled" id="pessoal">
                            <li><a href="{% url 'pessoas:cadastro' %}">> <span>Cadastro</span></a></li>
                            <li><a href="{% url 'militares:fatosobservados' %}">> <span>Fatos Observados</span></a></li>
                            <li><a href="{% url 'militares:destino' %}">> <span>Destinos</span></a></li>
                            <li><a href="{% url 'pessoas:listconscrito' %}">> <span>Comissão de Seleção</span></a></li>
                        </ul>
                    </li>
                {% endif %}
                <li>
                    <a href="#logistica" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fa fa-gears red_color"></i> <span>Logística</span></a>
                    <ul class="collapse list-unstyled" id="logistica">
                        <li><a href="{% url 'viaturas:viatura' %}">> <span>Viaturas</span></a></li>
                        <li><a href="{% url 'viaturas:armamento' %}">> <span>Armamentos</span></a></li>
                        <li><a href="{% url 'viaturas:dash_armt' %}">> <span>Painel Armt</span></a></li>
                        <li><a href="{% url 'viaturas:municao' %}">> <span>Munições</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

templates/topbar.html
{% load static %}
    <div class="topbar">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="full">
                    <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                <div class="logo_section">
                    <a href="#"><img class="img-responsive" src="{{ user.pessoas.militar.unidade.logo.url }}" alt="#" /></a>
                </div>
                <div class="right_topbar">
                    <div class="icon_info">
                        <ul class="user_profile_dd">
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown">
                                    {% if user.pessoas.foto %}
                                        <img class="img-responsive rounded-circle"
                                             src="{{ user.pessoas.foto.url }}"
                                             alt="#" /><span class="name_user">
                                    {% else %}
                                        <img class="img-responsive rounded-circle"
                                             src="{% static 'images/sem_img.png' %}"
                                             alt="#" /><span class="name_user">
                                    {% endif %}
                                    {% if user.pessoas.militar %}
                                    {{ user.pessoas.militar.nome_guerra }}
                                    {% elif user.pessoas %}
                                    {{ user.pessoas.nome_completo }}
                                    {% else %}
                                    {{ user }}
                                    {% endif %}
                                </span></a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'usuarios:perfil' user.id %}">Meu Perfil</a>
                                    {% if request.user.is_superuser %}
                                        <a class="dropdown-item" href="{% url 'quarteis:create_dados' %}">Criar Pessoas</a>
                                        <a class="dropdown-item" href="{% url 'quarteis:create_armt' %}">Criar Armamentos</a>
                                    {% endif %}
                                    <a class="dropdown-item" href="{% url 'usuarios:logout' %}"><span>Log Out</span> <i class="fa fa-sign-out"></i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>